### ISSUE TITLE
Does not support, what it says it supports.

### ISSUE THREAD

**Issue by SOELexicon** [dojo-engineering/Dojo.Net#1]
Spent a good amount of time going through the documentation only to find that this 

DOES NOT WORK _The official [Dojo](https://dojo.tech/) .NET library, supporting .NET Standard 2.0+, .NET Core 2.0+, and .NET Framework 4.6.1+._

this does not support .NET Framework at all. and the documentation on this is completely wrong.

i suggest changing the documentation to stop others wasting their time or fix it

**Comment by RomanKondratyev** [comment]
Hi @SOELexicon,

Sorry for a bit late reply - I will fix it.

Thanks,
Roman

**Comment by RomanKondratyev** [comment]
@SOELexicon  - I have updated the SDK to also support netstandard 20 and thus it works now for .net framework 4.6.1+. Please download version `1.0.8`.

**Comment by Imar** [comment]
Excellent, thanks, that makes the library a lot more useable! Thanks!
