### ISSUE TITLE
Not supported CardScheme enums

### ISSUE THREAD

**Issue by jsteff** [dojo-engineering/Dojo.Net#9]
**What is the issue?**

While using the SDK there are runtime errors because the current version is not up-to-date with the API.

The latest Dojo SDK has the CardScheme enum with the following values:

![image](https://github.com/dojo-engineering/Dojo.Net/assets/37579807/cdecbe37-1237-4868-8ad3-25fba60c8a0a)

And the API returns more than four supported card schemes:

![image](https://github.com/dojo-engineering/Dojo.Net/assets/37579807/f5e25981-21de-4cff-b552-571330642c79)

**Comment by AndreiMihalciuc** [comment]
@jsteff Thanks for letting us know about this issue. We are working on releasing a new version and we will let you know when it is ready

**Comment by AndreiMihalciuc** [comment]
@jsteff we have released a new version v1.1.1 please upgrade. Thanks again for reporting the issue
